# Site settings
title: H!Guo Technology Document
email: guohai at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This a chinese technology document repo,welcome your read and learning.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://guohai.org" # the base hostname & protocol for your site
twitter_username: freeguo
github_username:  guohai163

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jemoji

paginate: 12
paginate_path: "/page/:num"